In [ ]:
"""
NumPy Mini Project: “Student Grades Matrix” 

Simulate and analyze grades for a class using only NumPy.

Tasks:
1. Average grade per student	
2. Average grade per exam	
3. Highest grade overall	
4. Student with highest average
5. Add 5 bonus points to exam 2		
6. Grade range (max - min) for each student
7. Normalize the entire matrix (0–1 scale)	
"""

In [2]:
import numpy as np

# Rows = Students, Columns = Exams
grades = np.array([
    [88, 92, 79, 93],
    [76, 85, 83, 90],
    [90, 91, 94, 89],
    [67, 75, 78, 72],
    [85, 87, 90, 91]
])

In [5]:
#1
avg_grade_per_student = np.mean(grades, axis = 1)
print("Avg grade per student: ",avg_grade_per_student)

Avg grade per student:  [88.   83.5  91.   73.   88.25]


In [6]:
#2
avg_grade_per_exam = np.mean(grades, axis = 0)
print("Avg exam grade: ",avg_grade_per_exam)

Avg exam grade:  [81.2 86.  84.8 87. ]


In [7]:
#3
highest_grade = np.max(grades)
print(highest_grade)

94


In [22]:
#4
student_averages = np.mean(grades, axis=1)
index_of_highest_avg = np.argmax(student_averages)
print("Student with highest average (index):", index_of_highest_avg)

Student with highest average (index): 2


In [17]:
#5 
add_points_to_exam =  np.array([[5, 5, 5, 5]])
broadcasted = grades + add_points_to_exam
print(broadcasted)

[[93 97 84 98]
 [81 90 88 95]
 [95 96 99 94]
 [72 80 83 77]
 [90 92 95 96]]


In [20]:
#6
grade_range = np.ptp(grades, axis=1)
print("Grade range per student:", grade_range)

Grade range per student: [14 14  5 11  6]


In [21]:
#7
min_val = np.min(grades)
max_val = np.max(grades)

normalized_grades = (grades - min_val) / (max_val - min_val)
print("Normalized grades:\n", normalized_grades)

Normalized grades:
 [[0.77777778 0.92592593 0.44444444 0.96296296]
 [0.33333333 0.66666667 0.59259259 0.85185185]
 [0.85185185 0.88888889 1.         0.81481481]
 [0.         0.2962963  0.40740741 0.18518519]
 [0.66666667 0.74074074 0.85185185 0.88888889]]
