In [2]:
import numpy as np

a = np.array([1,2,3])
b = np.array([
            [1,2,3], 
            [4,5,6]
            ])
print("\n1D array: ", a)
print("Array dimension: ",a.ndim, " | Shape:", a.shape, "(Rows)")
print("\n2D array:\n", b)
print("Array dimension: ",b.ndim, " | Shape:", b.shape, "(Rows, Cols)")

c = a + b
print("\nSum of a + b arrays:\n", c)
print("Array dimension: ",c.ndim, " | Shape:", c.shape, "(Rows, Cols)")

d = np.array([
    [[2,4,6], 
     [8,10,12], 
     [14,16,18]]
    ])
print("\n3D array:\n", d)
print("Array dimension: ",d.ndim, " | Shape:", d.shape, "(Depth, Rows, Cols)")


1D array:  [1 2 3]
Array dimension:  1  | Shape: (3,) (Rows)

2D array:
 [[1 2 3]
 [4 5 6]]
Array dimension:  2  | Shape: (2, 3) (Rows, Cols)

Sum of a + b arrays:
 [[2 4 6]
 [5 7 9]]
Array dimension:  2  | Shape: (2, 3) (Rows, Cols)

3D array:
 [[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]]
Array dimension:  3  | Shape: (1, 3, 3) (Depth, Rows, Cols)


In [3]:
matrix = np.arange(25).reshape(5,5)
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [11]:
matrix2 = np.arange(25).reshape(5,5)
print(matrix2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [9]:
mean_all = np.mean(matrix)
print(mean_all)

12.0


In [4]:
row_averages = np.mean(matrix, axis=1)
print("Row averages: ", row_averages)

Row averages:  [ 2.  7. 12. 17. 22.]


In [5]:
column_averages = np.mean(matrix, axis=0)
print("Column averages: ", column_averages)

Column averages:  [10. 11. 12. 13. 14.]


In [6]:
sum_all = np.sum(matrix)
print(sum_all)

300


In [7]:
sum_rows = np.sum(matrix, axis=1)
print(sum_rows)

[ 10  35  60  85 110]


In [8]:
sum_colums = np.sum(matrix, axis=0)
print(sum_colums)

[50 55 60 65 70]


In [10]:
max_columns = np.max(matrix, axis=0)
print(max_columns)

[20 21 22 23 24]


In [16]:
index_of_max = np.argmax(matrix)
print("Index of max: ", index_of_max)

coords = np.unravel_index(index_of_max, matrix.shape)
print("Max value is at: ", coords)

Index of max:  24
Max value is at:  (4, 4)


In [11]:
var_all = np.var(matrix)
print(var_all)

52.0


In [18]:
value = matrix[2,3]
print(value)

13


In [19]:
first_row = matrix[0]
print(first_row)

[0 1 2 3 4]


In [20]:
last_column = matrix[:, -1]
print(last_column)

[ 4  9 14 19 24]


In [21]:
center = matrix[1:4, 1:4]
print(center)

[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


In [23]:
reversed_rows = matrix[::-1]
print(reversed_rows)

[[20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


In [24]:
matrix[0] = 99
print(matrix)

[[99 99 99 99 99]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [25]:
flat = matrix.flatten()
print(flat)

[99 99 99 99 99  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [26]:
colum_vec = flat.reshape(25, 1)
print(colum_vec)

[[99]
 [99]
 [99]
 [99]
 [99]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]


In [27]:
fives_row = np.array([5, 5, 5, 5, 5])
broadcasted = matrix + fives_row
print(broadcasted)

[[104 104 104 104 104]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]]


In [29]:
col = np.array([[0], [1], [2], [3], [4]])
result = matrix - col
print(result)

[[99 99 99 99 99]
 [ 4  5  6  7  8]
 [ 8  9 10 11 12]
 [12 13 14 15 16]
 [16 17 18 19 20]]


In [30]:
stacked = np.vstack([matrix, matrix])
print(stacked)

[[99 99 99 99 99]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [99 99 99 99 99]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [31]:
side_by_side = np.hstack([matrix, matrix])
print(side_by_side)

[[99 99 99 99 99 99 99 99 99 99]
 [ 5  6  7  8  9  5  6  7  8  9]
 [10 11 12 13 14 10 11 12 13 14]
 [15 16 17 18 19 15 16 17 18 19]
 [20 21 22 23 24 20 21 22 23 24]]
