In [18]:
import torch

x = torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


In [19]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print(a + b)
print(a * b)
print(torch.matmul(a, b))


tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor(32)


In [20]:
rand = torch.rand(2,3) # Rows, Columns
print(rand)

tensor([[0.4056, 0.3968, 0.0370],
        [0.4279, 0.8111, 0.5298]])


In [21]:
zeros = torch.ones(2, 3)
print(zeros)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [24]:
import numpy as np

# Works well with numpy
arr = np.array([1,2,3])
tensor = torch.from_numpy(arr)
back = tensor.numpy()

print(arr)
print(tensor)
print(back)

[1 2 3]
tensor([1, 2, 3])
[1 2 3]
